---
# ENERGY
-
  title: Wind Power
  cost: 4/2$
  keywords: [ENERGY, Renewable, Variable, Clean]
  right_value: +0P
  flavour: Tilting at windmills is fun.
  count: 5
-
  title: Solar Power
  cost: 4/2$
  keywords: [ENERGY, Renewable, Variable, Clean]
  image: sun
  right_value: +0P
  flavour: Remote fusion generator.
  count: 5
-
  title: Nuclear Power
  cost: 3$
  keywords: [ENERGY, Clean, (Tsunami)]
  image: radiation
  right_value: +0P
  flavour: Nuclear energy is perfectly safe...most of the time.
  count: 3
-
  title: Fracking
  cost: 1$
  keywords: [ENERGY, Hydrocarbon, (Earthquakes)]
  left_value: +1$
  right_value: +2P
  count: 2
-
  title: Biomass
  cost: 3$
  keywords: [ENERGY]
  left_value: +1$
  right_value: +1P
  count: 2


# Disaster Defences
-
  title: Coastal Defences
  keywords: [Protection]
  cost: 2$
  text: |
    Reduces effect of
    Rising Sea Levels by 2$
  count: 2
-
  title: Defence-2
  keywords: [Protection]
  cost: 2$
  text: |
    Reduces effect of
    Disaster-2 by 2$
  count: 2
-
  title: Defence-3
  keywords: [Protection]
  cost: 2$
  text: |
    Reduces effect of 
    Disaster-3 by 2$
  count: 2

# General cards
-
  title: SO₂ Scrubbers
  cost: 1$
  text: |
    Coal
    ENERGY
  center_icon: then
  right_value: -1P
  flavour: Sulphur dioxide in the atmosphere creates acid rain, but also slows global warming!
  count: 4
-
  title: Development
  cost: 2$
  text: Other player
  center_icon: then
  right_value: +3$
  count: 2
-
  title: Electric cars
  cost: 3$
  text: |
    Clean
    ENERGY
  center_icon: then
  right_value: -1P
  flavour: Electric cars don’t actually reduce overall pollution themselves! They only reduce emissions where they are driven and move them to where the electricity is generated.
  count: 2
-
  title: Public Transport
  cost: 4$
  right_value: -1P
  count: 3
-
  title: Large Scale Storage
  cost: 4/2$
  text: |
    Variable
    ENERGY
  center_icon: then
  right_value: -1P
  flavour: Improve renewables that are not “always on” by storing energy, for example in electric batteries.
  count: 2
-
  title: Reforestation
  keywords: [Optional]
  cost: 1$
  left_value: -$
  center_icon: then
  right_value: -1P
  count: 2
-
  title: Cleanup
  keywords: ["INSTANT"]
  cost: 4$
  text: Instant
  right_value: -4P
  count: 4
-
  title: Ocean Cleaning Ship
  keywords: [Optional]
  cost: 2$
  left_value: -1$
  center_icon: then
  right_value: -1P
  count: 2
-
  title: Recycling
  cost: 4$
  right_value: -1P
  flavour: Recycling is for the super cool kids. No-one else need bother!
  count: 2
-
  title: Sustainability
  cost: 4$
  right_value: -1P
  count: 2
-
  title: Green-washing
  cost: 3$
  text: |
    Hydrocarbon
    ENERGY
  center_icon: then
  right_value: +1$
  flavour: Sell more, at higher prices, by simply convincing the public that you are environmentally conscious.
  count: 2
-
  title: Trash-digestion
  cost: 4$
  right_value: -1P
  flavour: Engineer genetically modified bacteria that like eating waste, such as plastics.
-
  title: Fusion Research
  keywords: [Risky]
  cost: 5$
  text: |
    Round 10
    only
  center_icon: coin flip
  right_value: -9P
-
  title: Built In Obsolescence
  cost: 0$
  left_value: +1$
  right_value: -1P
  flavour: Make things that break quickly and can’t be repaired, so we need to buy new ones.
  count: 2
-
  title: Razing Rainforests
  cost: -3$
  keywords: ["INSTANT"]
  text: Instant
  right_value: +3P
  flavour: Destroying habitats through deforestation for short-term agricultural productivity of, for example, palm oil.
  count: 2
-
  title: Outsourcing Prod.
  cost: 3$
  left_value: +2$
  right_value: +2P
  flavour: Sending factories to developing countries reduces costs, but creates humanitarian abuses and unnecessary pollution.
  count: 2
-
  title: Renewable Subsidies
  keywords: [INSTANT, Global]
  cost: 2$
  center_icon: global
  text: | 
    Renewable 
    ENERGY
  right_value: +1$
  count: 2
-
  title: Aviation Subsidies
  keywords: [INSTANT, Global]
  cost: 2$
  text: |
    Hydrocarbon
    ENERGY
  center_icon: global
  right_value: +1$
  count: 2

