---
# One sheet for the landscape cards, arranged so they match the cards on the front.
-
  count: 4
  card_type: Player
-
  count: 1
  card_type: Disaster
-
  count: 1
  card_type: Player
-
  count: 2
  card_type: Disaster
-
  count: 16  # 2 sheets
  card_type: Event
-
  count: 10  # 2 sheets
  card_type: Starting
-
  count: 6
  is_blank: true
-
  count: 64  # 8 sheets




