---
-
  title: Rising Sea Levels
  keywords: [EVENT, Global]
  center_icon: global
  right_value: -X$
  count: 3
-
  title: Disaster-2
  keywords: [EVENT, Global]
  center_icon: global
  right_value: -X$
  count: 3
-
  title: Disaster-3
  keywords: [EVENT, Global]
  center_icon: global
  right_value: -X$
  count: 3
-
  title: Tsunami
  keywords: [EVENT, Global]
  text: |
    Nuclear
    Power
  center_icon: global
  right_value: -X$
  count: 1
-
  title: Earthquakes
  keywords: [EVENT, Global]
  text: |
    Fracking
  center_icon: global
  right_value: -X$
  count: 1
-
  title: Global Pandemic
  keywords: [EVENT, Global]
  center_icon: global
  right_value: -2$
  count: 1
-
  title: Imperialist War
  keywords: [EVENT]
  right_value: +2P
  count: 1
-
  title: Major Oil Spill
  keywords: [EVENT]
  right_value: +2P
  count: 1
-
  title: Renewable Subsidies
  keywords: [EVENT, Global]
  center_icon: global
  text: | 
    Renewable 
    ENERGY
  right_value: +1$
  count: 2
-
  title: Aviation Subsidies
  keywords: [EVENT, Global]
  text: |
    Hydrocarbon
    ENERGY
  center_icon: global
  right_value: +1$
  count: 2
-
  title: Nothing Happens
  keywords: [EVENT]
  flavour: Something incredibly unimportant happens to a Hollywood star. Everyone will have forgotten about it by tomorrow!
  count: 1
-
  title: Nothing Happens
  keywords: [EVENT]
  flavour: A dog was lost and found at the bottom of a well. All was well!
  count: 1