---
-
  name: The Big Pear
  image: pear
  initial:
    prosperity: 4
    pollution: 8
  income:
    prosperity: 3
    pollution: 2
  flavour: Makes flashy thinking machines and spews out microplastics and heavy metals. Public perception of their luxury goods is more important than anything else.
-
  name: The Little Bean
  image: pear
  initial:
    prosperity: 0
    pollution: 0
  income:
    prosperity: 3
    pollution: 2
  flavour: Barely has two beans to rub together.
-
  name: Player-3
  image: pear
  initial:
    prosperity: 2
    pollution: 4
  income:
    prosperity: 3
    pollution: 2
  flavour: ""
-
  name: Player-4
  image: pear
  initial:
    prosperity: 2
    pollution: 4
  income:
    prosperity: 3
    pollution: 2
  flavour: ""
-
  name: Player-5
  image: pear
  initial:
    prosperity: 2
    pollution: 4
  income:
    prosperity: 3
    pollution: 2
  flavour: ""
