---
-
  title: Break the Law!
  text: Due to violating environmental law, your equipment is auctioned off. First person to clap claims 1 energy producer or 1 tree.
-
  title: Pariah!
  text: A company refused to offer you their services. First person to clap may take a random card from your hand.
-
  title: Abandoned!
  text: You lost 10% of your customers. Lose a turn!
-
  title: Strike action!
  text: Your workers went on strike; miss a turn!
-
  title: Rent!
  text: You need to pay rent. You have $2 less to spend on your next mineral purchase.
-
  title: Disapproval
  text: (Write your own effect, below)
  count: 2
