---
-
  cost: 2
  image: ore1
  value: 1$
  count: 6
-
  cost: 2
  image: granite
  value: 1E
  count: 1
-
  cost: 2
  image: stone
  value: 1T
  count: 1
-
  cost: 3
  image: coal69
  value: 2$
  count: 3
-
  cost: 3
  image: ore2
  value: 1E 1T
  count: 2
-
  cost: 3
  image: stones
  value: 1$ 1T
  count: 2
